# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0005_auto_20160409_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('name', models.CharField(default='File', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FileField(blank=True, upload_to='uploads/expense/%Y/%m/%d/')),
                ('amount', models.IntegerField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('employee', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='homepage.Employee_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_source', models.CharField(blank=True, max_length=50)),
                ('trip_destination', models.CharField(blank=True, max_length=50)),
                ('trip_distance', models.IntegerField(blank=True)),
                ('trip_shipper', models.CharField(blank=True, max_length=50)),
                ('trip_consignee', models.CharField(blank=True, max_length=50)),
                ('trip_goods_type', models.CharField(blank=True, max_length=50)),
                ('trip_container_number', models.CharField(blank=True, max_length=50)),
                ('trip_weight', models.IntegerField(default=100)),
                ('trip_start_date', models.DateField(default=datetime.date.today)),
                ('trip_end_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Tripsearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_search_item', models.CharField(max_length=300)),
                ('trip_type', models.CharField(choices=[('trip_source', 'Trip Source'), ('trip_date', 'Trip Date'), ('truck_registration_number', 'Truck Number')], default='Trip Source', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_registration_number', models.CharField(max_length=20, unique=True)),
                ('truck_driver', models.CharField(max_length=50)),
                ('truck_type', models.CharField(choices=[('Semi-trailer', 'SEMI-TRAILER'), ('Trailer', 'TRAILER'), ('Box-Body', 'BOX-BODY')], default='TRAILER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TruckDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('document_name', models.CharField(max_length=30)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Truck')),
            ],
        ),
        migrations.CreateModel(
            name='Trucksearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_search_item', models.CharField(max_length=300)),
                ('truck_type', models.CharField(choices=[('truck_registration_number', 'Truck registration number'), ('truck_driver', 'Truck Driver')], default='Truck Driver', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='truck_registration_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Truck'),
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Trip'),
        ),
        migrations.AddField(
            model_name='document',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Trip'),
        ),
    ]
