# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('name', models.CharField(default='File', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_source', models.CharField(blank=True, max_length=50)),
                ('trip_destination', models.CharField(blank=True, max_length=50)),
                ('trip_distance', models.IntegerField(blank=True)),
                ('trip_shipper', models.CharField(blank=True, max_length=50)),
                ('trip_consignee', models.CharField(blank=True, max_length=50)),
                ('trip_goods_type', models.CharField(blank=True, max_length=50)),
                ('trip_container_number', models.IntegerField(blank=True)),
                ('trip_weight', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_registration_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('truck_driver', models.CharField(max_length=50)),
                ('truck_type', models.CharField(choices=[('Semi-trailer', 'SEMI-TRAILER'), ('Trailer', 'TRAILER'), ('Box-Body', 'BOX-BODY')], default='TRAILER', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='truck_registration_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Truck'),
        ),
        migrations.AddField(
            model_name='document',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Trip'),
        ),
    ]
