# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_consignee',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_container_number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_goods_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_weight',
        ),
    ]
