# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20160308_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FileField(upload_to='uploads/expense/%Y/%m/%d/')),
                ('amount', models.IntegerField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Trip')),
            ],
        ),
    ]
