# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 08:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20160414_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Employee_Detail'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_end_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_start_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_weight',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
