# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20160415_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='employee',
        ),
        migrations.AlterField(
            model_name='tripsearch',
            name='trip_type',
            field=models.CharField(choices=[('trip_source', 'Trip Source'), ('trip_start_date', 'Trip Start Date'), ('trip_end_date', 'Trip End Date'), ('trip_destination', 'Trip Destination'), ('trip_goods_type', 'Goods Type'), ('trip_container_number', 'Container Number')], default='Trip Source', max_length=100),
        ),
        migrations.AlterField(
            model_name='trucksearch',
            name='truck_type',
            field=models.CharField(choices=[('truck_registration_number', 'Truck registration number'), ('truck_type', 'Truck Type')], default='Truck Driver', max_length=100),
        ),
    ]
