# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 05:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_consignee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_container_number',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_goods_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_weight',
            field=models.IntegerField(default=100),
        ),
    ]
