# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_expense_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('document_name', models.CharField(max_length=30)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Truck')),
            ],
        ),
    ]
