# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_truckdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip_date',
            new_name='trip_start_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bill',
            field=models.FileField(blank=True, upload_to='uploads/expense/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_container_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
