# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_auto_20160407_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripsearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_search_item', models.CharField(max_length=300)),
                ('trip_type', models.CharField(choices=[('trip_source', 'Trip Source'), ('trip_date', 'Trip Date'), ('truck_registration_number', 'Truck Number')], default='Trip Source', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trucksearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_search_item', models.CharField(max_length=300)),
                ('truck_type', models.CharField(choices=[('truck_registration_number', 'Truck registration number'), ('truck_driver', 'Truck Driver')], default='Truck Driver', max_length=100)),
            ],
        ),
    ]
