# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('name', models.CharField(default='File', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_type', models.CharField(default='Oil', max_length=100)),
                ('good_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(blank=True, max_length=100)),
                ('from_company', models.CharField(blank=True, max_length=100)),
                ('import_date', models.DateField(default=datetime.date.today)),
                ('trasaction_type', models.CharField(choices=[('Import', 'Import'), ('Export', 'Export')], default='Import', max_length=10)),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Goods')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='transaction_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Transaction'),
        ),
    ]
