# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='goods_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
