# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_transaction_goods_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='import_date',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='trasaction_type',
            new_name='transaction_type',
        ),
    ]
