# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20160315_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodssearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_search_item', models.CharField(max_length=300)),
                ('good_type', models.CharField(choices=[('good_type', 'Good Type'), ('good_quantity', 'Good Quantity')], default='Good Type', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transactionsearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_search_item', models.CharField(max_length=300)),
                ('transaction_type', models.CharField(choices=[('reference_name', 'Reference Name'), ('from_company', 'Import Company'), ('transaction_type', 'Transaction type'), ('goods_type', 'Goods Type')], default='Transaction Type', max_length=100)),
            ],
        ),
    ]
