# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20160415_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsearch',
            name='transaction_type',
            field=models.CharField(choices=[('reference_name', 'Reference Name'), ('from_company', 'Import Company'), ('transaction_type', 'Transaction type'), ('transaction_date', 'Transaction Date')], default='Transaction Type', max_length=100),
        ),
    ]
