# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 18:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(unique=True)),
                ('currency_type', models.CharField(choices=[('Uganda Shilling', 'Uganda Shilling'), ('USD', 'USD'), ('Euro', 'Euro'), ('Kenya Shillings', 'Kenya Shillings'), ('Congolese Franc', 'Congolese Franc'), ('Rwanda Franc', ' Rwanda Franc'), ('INR', 'INR')], default='USD', max_length=20)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('transaction_details', models.TextField()),
                ('transaction_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=10)),
                ('transaction_amount', models.IntegerField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
