# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_employee_detail_cash_in_hand'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_added', models.IntegerField()),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('transaction_details', models.TextField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Employee_Detail')),
            ],
        ),
    ]
