# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeecash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
