# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160406_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='BankAccount',
        ),
    ]
