# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160407_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeCash',
            new_name='EmployeeCashBook',
        ),
    ]
