# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_transaction_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountssearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_search_item', models.CharField(max_length=300)),
                ('account_type', models.CharField(choices=[('account_number', 'Account Number'), ('amount', 'Amount')], default='Account Number', max_length=100)),
            ],
        ),
    ]
