# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bankaccountssearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
