# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160410_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='currency_type',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_holder',
            field=models.CharField(default='Company', max_length=100),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(default=b'2016-04-11 22:10:13.269766+00:00', max_length=100),
            preserve_default=False,
        ),
    ]
