# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20160320_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_detail',
            name='cash_in_hand',
            field=models.IntegerField(default=0),
        ),
    ]
