# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_employee_detail_cash_in_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Important', 'Important'), ('Urgent', 'Urgent'), ('Normal Priority', 'Normal Priority')], default='Normal Priority', max_length=20),
        ),
    ]
