# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20160409_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasksearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_search_item', models.CharField(max_length=300)),
                ('tasksearch_type', models.CharField(choices=[('assigned_to', 'Assigned To'), ('assigned_on', 'Assigned on'), ('deadline', 'Deadline')], max_length=20)),
            ],
        ),
    ]
