# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20160407_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('invoiced_to', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('vat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('receipt_from', models.CharField(max_length=100)),
                ('amount_received', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Cheque', 'Cheque'), ('Cash', 'Cash')], default='Cash', max_length=30)),
                ('balance', models.IntegerField()),
                ('credited_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BankAccount')),
                ('payment_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.Invoice')),
            ],
        ),
    ]
