# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoicesearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_search_item', models.CharField(max_length=300)),
                ('invoicesearch_type', models.CharField(choices=[('invoice_number', 'Invoice Number'), ('date', 'Date'), ('invoiced_to', 'Invoiced To'), ('quantity', 'Quantity'), ('unit_price', 'Unit Price'), ('total_price', 'Total Price'), ('vat', 'VAT')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Receiptsearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_search_item', models.CharField(max_length=300)),
                ('receiptsearch_type', models.CharField(choices=[('receipt_number', 'Receipt Number'), ('receipt_from', 'Receipt From'), ('payment_mode', 'Payment Mode'), ('credited_to', 'Credited To'), ('balance', 'Balance'), ('date', 'Date')], max_length=20)),
            ],
        ),
    ]
